server:
  port: 8761

spring:
  jmx:
    default-domain: mogu_eureka
  security:
    user:
      name: user
      password: password123

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password123@10.8.0.245:8761/eureka