#app
server:
  port: 8604

#阿里大于
accessKeyId: LTAI99t3H0yGpC8E#修改成自己的
accessKeySecret: RQVwPjFJks3v8ZgIYvFRjDN2KXar9U#修改成自己的



#spring
spring:
  jmx:
    default-domain: mogu_sms
  thymeleaf:
    cache: true   #关闭缓存
  application:
    name: mogu-sms

  #redis
  redis:
    host: 10.8.0.245 #redis的主机ip
    port: 16379

  #RabbitMq
  rabbitmq:
    host: 10.8.0.245 #rabbitmq的主机ip
    port: 5672
    username: admin
    password: admin

  #Solr
  data:
    solr:
      host: http://10.8.0.245:32789/solr
      core: solr
      repositories:
        enabled: true

    #mail
  mail:
    username: corewhq@126.com
    password: 13785031967p #授权码开启SMTP服务里设置
    host: smtp.126.com

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@10.8.0.245:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为
    lease-renewal-interval-in-seconds: 5
